[package]
name = "wasm-module1"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ['cdylib']

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"